-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    id uuid NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(50),
    family uuid NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT customer_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.customer_family
(
    id uuid NOT NULL,
    code character varying(20) NOT NULL,
    description character varying(255),
    PRIMARY KEY (id),
    CONSTRAINT customer_family_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    id uuid NOT NULL,
    customer uuid NOT NULL,
    product uuid NOT NULL,
    quantity integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id uuid NOT NULL,
    code character varying(20) NOT NULL,
    designation character varying(255),
    PRIMARY KEY (id),
    CONSTRAINT product_code UNIQUE (code)
);

ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT family FOREIGN KEY (family)
    REFERENCES public.customer_family (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT customer FOREIGN KEY (customer)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT product FOREIGN KEY (product)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;